LOCAL_SERVER_HOST               = '212.22.92.159'
LOCAL_SERVER_PORT               = 30000
LOCAL_SERVER_PORT_COUNT         = 10
LOCAL_SERVER_CLIENT_TIMEOUT     = 10

MEDIATOR_SERVER_HOST            = '212.22.92.159'
MEDIATOR_SERVER_PORT            = 30010
MEDIATOR_SERVER_HOST_TO_SEND    = LOCAL_SERVER_HOST
MEDIATOR_SERVER_PORT_TO_SEND    = LOCAL_SERVER_PORT
MEDIATOR_SERVER_SOCKET_TIMEOUT  = 10

LORA_IMITATION_HOST_TO_SEND     = MEDIATOR_SERVER_HOST
LORA_IMITATION_PORT_TO_SEND     = MEDIATOR_SERVER_PORT
