# Generated by Django 2.0.5 on 2018-05-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'carriers',
            },
        ),
        migrations.CreateModel(
            name='PositionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('alarm_button', models.CharField(max_length=1)),
                ('carrier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Carrier')),
            ],
            options={
                'db_table': 'position_data',
            },
        ),
    ]
