# Generated by Django 2.0.5 on 2018-05-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positiondata',
            old_name='carrier_id',
            new_name='carrier',
        ),
    ]
