# Generated by Django 2.0.5 on 2018-05-30 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_carrier_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 14, 58, 15, 90323)),
        ),
    ]
