# Generated by Django 2.0.5 on 2018-05-30 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20180530_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positiondata',
            old_name='carrier',
            new_name='carrier_id',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 15, 1, 27, 383256)),
        ),
    ]
