# Generated by Django 2.0.5 on 2018-05-30 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_auto_20180530_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='positiondata',
            old_name='carrier_id',
            new_name='carrier',
        ),
        migrations.AlterField(
            model_name='carrier',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 15, 22, 59, 740675)),
        ),
    ]
