# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeFOUND', '0002_auto_20170503_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralarmbutton',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
