# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeFOUND', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userab',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
