# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeFOUND', '0003_auto_20170503_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='alarm_button',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BeFOUND.AlarmButton'),
            preserve_default=False,
        ),
    ]
