# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeFOUND', '0004_coordinates_alarm_button'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedAlarmButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_begin', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'used_alarm_button',
            },
        ),
        migrations.RemoveField(
            model_name='useralarmbutton',
            name='alarm_button',
        ),
        migrations.RemoveField(
            model_name='useralarmbutton',
            name='user',
        ),
        migrations.AlterField(
            model_name='alarmbutton',
            name='users',
            field=models.ManyToManyField(related_name='alarm_buttons', through='BeFOUND.UsedAlarmButton', to='BeFOUND.UserAB'),
        ),
        migrations.DeleteModel(
            name='UserAlarmButton',
        ),
        migrations.AddField(
            model_name='usedalarmbutton',
            name='alarm_button',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeFOUND.AlarmButton'),
        ),
        migrations.AddField(
            model_name='usedalarmbutton',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_buttons', to='BeFOUND.UserAB'),
        ),
    ]
